Homework3
made-mlops-2022/maksim_pakhomov pull request #3
Opened 2022-11-29 17:05 UTC by AverageName

1. Dag для скачки даты каждый день реализован (5 баллов)
2. Dag, который еженедельно обучает модельку реализован (10 баллов)
3. Dag для предикта каждый день реализован (5 баллов)
4. Все Dag'и реализованы с помощью DockerOperator (10 баллов)
5. Самооценка (1 балл)

Доп:
1. Реализованы сенсоры (3 балла)
Сумма: 34 балла

2022-12-04 13:54 UTC, bulaevvi commented
Без скриншотов баллы начислены не будут. Читайте внимательно задание

2022-12-04 14:12 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста". У Вас нет скриншотов каждого отдельного дага в исполненном виде. Без этого баллы не будут начислены

2022-12-04 15:19 UTC, AverageName commented
Сегодня постараюсь приложить, упустил этот момент как-то, извиняюсь

2022-12-05 20:21 UTC, AverageName commented
Локально развернутый airflow
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/30757789/205735311-a7548ab4-b4ef-4f95-b091-063abf73d3d3.png">

2022-12-05 20:23 UTC, AverageName commented
Исполненный DAG скачки данных
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/30757789/205735773-c93f306b-5cc6-4161-a2e6-875d4c8b9953.png">
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/30757789/205735812-36b950b0-adc3-475e-af08-5cc06e889676.png">

2022-12-05 20:24 UTC, AverageName commented
Исполненный DAG тренировки
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/30757789/205735935-bda191f8-72a2-45d8-b9a2-cc15a24e6f3e.png">
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/30757789/205735970-b458edae-64cc-4fc1-bf87-8ce439095ffd.png">

2022-12-05 20:28 UTC, AverageName commented
Исполненный DAG предикта
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/30757789/205736616-9aba6b3e-3b12-45a5-8b1b-011089f81dd8.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/30757789/205736655-88d8da67-5868-4d27-8105-01e15fc4ff03.png">

2022-12-06 03:10 UTC, bulaevvi commented
Эти скриншоты не подходят. Посмотрите примеры, которые я привел в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-06 07:20 UTC, AverageName commented
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/30757789/205846360-db0de8a7-7c43-4ab2-86ed-7d068d743ed4.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/30757789/205846480-65809e9d-8bfe-4f0b-8c31-03c8cc7c99b9.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/30757789/205846532-c2f2fb05-867a-43e6-90e4-e14d45786c3e.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/30757789/205846578-2ac8eea0-7f86-4385-b4bd-a3879c34a821.png">

2022-12-06 07:27 UTC, bulaevvi approved these changes
Итого 34 балла. Делайте merge

2022-12-06 08:07 UTC, merged